server: 
  port: 8083

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=DBCOAST;integratedSecurity=false;sendStringParametersAsUnicode=false
    username: sa
    password: Password@123
    
  security:
    user:
      name: wolf
      password: hj965691203
      
  thymeleaf:
    cache: false
    mode: HTML5
    